### ISSUE TITLE
How to split lines?

### ISSUE THREAD

**Issue by Thieund** [JungWinter/split#15]
Which value should I put into "seperator" to split a file content into lines?

**Comment by winterjung** [comment]
@Thieund Hi! Could you try sep**a**rator with `"\n"`? (In `@v2`, `sep`**`e`**`rator` input is renamed to `sep`**`a`**`rator`

```yaml
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: 'something\nmulti line texts you want'
          separator: '\n'
```
