### ISSUE TITLE
String not being split by '/' delimiter

### ISSUE THREAD

**Issue by alexthaii** [JungWinter/split#19]
I have a string `folder/subfolder/file.yml` and I'd like to split it by `/`. When I print the result, it gives me the whole string rather then `folder`/

**Workflow Snippet**
```
- uses: jungwinter/split@v2.0.0
  id: split
  with:
    msg: ${{ steps.filter.outputs.changes_files }}
    separator: '/'

- name: Get application's name
  id: app_name
  run: |
    echo ${{ steps.split.outputs._0 }}
```

**Output Logs**
```
Run jungwinter/split@v2.0.0
  with:
    msg: folder/subfolder/file.yml
    separator: /
    maxsplit: -1

Run echo folder/subfolder/file.yml
  echo folder/subfolder/file.yml
```
