### ISSUE TITLE
Something is wrong on split

### ISSUE THREAD

**Issue by DatL4g** [JungWinter/split#20]
I currently switched from https://github.com/marketplace/actions/simple-split and something is off.

I'm using another action to sign a list of files.
This will produce a string of the full path to the signed files, separated by a `:`.

The signing output string looks like this:
`/home/runner/work/Burning-Series/Burning-Series/app/release/app-release-signed.aab:/home/runner/work/Burning-Series/Burning-Series/app/release/app-release-signed.apk`

My split config looks like this:

```yml
- name: Split signed files
  uses: JungWinter/split@v2.1.0
  id: split
  with:
    msg: ${{ steps.sign_app.outputs.signedFiles }}
    separator: ':'
    maxsplit: 2
```

When I try to upload the files by their split path it can't find the first file.

So it tries to resolve `/github/workspace/app/release/app-release-signed.aab` but can't find it

**However it works with the second file**

You can take a look at the job here: https://github.com/DATL4G/Burning-Series/actions/runs/4398432795/jobs/7702280605
