### ISSUE TITLE
Unexpected input(s) 'seperator', valid inputs are ['entryPoint', 'args', 'msg', 'separator', 'maxsplit']

### ISSUE THREAD

**Issue by zerofo** [JungWinter/split#25]
action:
```
- name: Extract owner and repo
      uses: winterjung/split@v2.1.0
      id: repo
      with:
        msg: ${{ github.repository }}
        seperator: '/'
```
log:
```
Warning: Unexpected input(s) 'seperator', valid inputs are ['entryPoint', 'args', 'msg', 'separator', 'maxsplit']
Run winterjung/split@v[2](https://github.com/*/*/actions/runs/9943513555/job/27467520910#step:4:2).1.0
  with:
    msg: */*
    seperator: /
    separator:  
    maxsplit: -1
```
